import * as cheerio from 'cheerio';
import { initializeApp } from 'firebase/app';
import { getFirestore, doc, updateDoc, setDoc, getDoc } from 'firebase/firestore';

// 1. Firebase Ledger Config
const firebaseConfig = {
    apiKey: "AIzaSyD0q99R9wn-r6e5aygL2zzg7e-Gc439ssY",
    authDomain: "cometchat-ai-platform.firebaseapp.com",
    projectId: "cometchat-ai-platform",
    storageBucket: "cometchat-ai-platform.firebasestorage.app",
    messagingSenderId: "604438924597",
    appId: "1:604438924597:web:a180d59f7f00385138507c"
};

export default async function handler(req, res) {
    res.setHeader('Access-Control-Allow-Credentials', true);
    res.setHeader('Access-Control-Allow-Origin', '*'); 
    res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
    res.setHeader('Access-Control-Allow-Headers', 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version');

    if (req.method === 'OPTIONS') {
        return res.status(200).end();
    }

    if (req.method !== 'POST') {
        return res.status(405).json({ success: false, message: 'Method Not Allowed' });
    }

    try {
        const { businessId, url } = req.body;

        if (!url || !businessId) {
            return res.status(400).json({ success: false, message: 'Missing businessId or URL.' });
        }

        // 2. Fetch the target website target matrix
        const response = await fetch(url, {
            headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) ComexAI/1.0' }
        });
        
        if (!response.ok) {
            throw new Error(`Failed to fetch target website. Status: ${response.status}`);
        }

        const html = await response.text();
        const $ = cheerio.load(html);

        // Clean out code junk from the DOM tree
        $('script, style, nav, footer, iframe').remove();
        const extractedText = $('body').text().replace(/\s\s+/g, ' ').trim();

        if (!extractedText || extractedText.length < 10) {
            throw new Error("Scraper warning: Extracted text is too short or empty.");
        }

        // 3. 🌟 CRITICAL: Save the text matrix directly to Firebase!
        const app = initializeApp(firebaseConfig);
        const db = getFirestore(app);
        const docRef = doc(db, "user_bots", businessId);

        // Check if the document already exists from the frontend step
        const docSnap = await getDoc(docRef);
        
        if (docSnap.exists()) {
            // If the document is already generated by the client layout, update the context field
            await updateDoc(docRef, { context: extractedText });
        } else {
            // Otherwise, create a fallback entry profile
            await setDoc(docRef, {
                id: businessId,
                url: url,
                context: extractedText,
                createdAt: new Date().toISOString()
            });
        }
        
        return res.status(200).json({
            success: true,
            message: `Matrix cloud sync complete for ${url}. Database updated.`,
            characterCount: extractedText.length,
            snippet: extractedText.substring(0, 200) + "..."
        });

    } catch (error) {
        console.error("Scraper Engine Failure:", error);
        return res.status(500).json({ success: false, message: error.message });
    }
}
